version: '3.8'

services:
  service-registry:
    image: my-eureka-service-registry:latest
    container_name: service-registry-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=Service_Registry
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=120
